
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import filedialog
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import pygame
import time
import threading
from test import *
from tkinter import filedialog
import cv2
from PIL import Image, ImageTk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk
OUTPUT_PATH = Path(__file__).parent #đường dẫn đến thư mục bulid_GUI
list_key=[]
content=''
id=''
description=''
running=True
#status_thread_2=True 
def keys_api():
    global list_key
    gc = gspread.service_account(filename='api_sheet.json')
    wks = gc.open("API_chatgpt").sheet1
    list_key=wks.col_values(1)
    list_key = [value for value in list_key if value != ""]
    return list_key

thread_key=threading.Thread(target=keys_api)
thread_key.start()
thread_key.join()

def import_file(list_key):
    global content
    file_path = filedialog.askopenfilename(filetypes=[("Word Files", "*.docx")])
    print(file_path)
    content= read_docx(file_path,list_key)
    return content

def audio():
    global running
    index_speech=-1
    index_content=-1
    pygame.init()
    pygame.mixer.init()
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
        if not pygame.mixer.music.get_busy():
            url_new,_,index_speech,index_content=urf_file_speech_continue(index_speech,index_content)
            pygame.init()
            pygame.mixer.init()
            pygame.mixer.music.load(url_new)
            time.sleep(0.5)
            pygame.mixer.music.play()
    pygame.mixer.music.stop()
    pygame.quit()

def button_run():
    canvas_gui3.pack_forget()
    remove_data(r'speech_folder')
    thread_1 = threading.Thread(target=process_thread_1,args=[id,])
    thread_2 = threading.Thread(target=process_thread_2,args=[content,description,list_key])
    #thread_3 = threading.Thread(target=GUI)
    thread_3 = threading.Thread(target=audio)
    thread_1.start()
    thread_2.start()
    thread_3.start()
    main_1()
    thread_1.join()
    thread_2.join()
    thread_3.join()

def button_gui5():
    global running
    running=False
    remove_data(r'speech_folder')


window = Tk()
window.geometry("1177x659")
window.configure(bg = "#FFFFFF")
#GUI1
canvas_gui1 = Canvas(
    window,
    bg = "#FFFFFF",
    height = 659,
    width = 1177,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
#canvas_gui1.place(x = 0, y = 0)
#GUI2
canvas_gui2 = Canvas(
    window,
    bg = "#FFFFFF",
    height = 662,
    width = 1175,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
#GUI2 BS
canvas_gui2bs = Canvas(
    window,
    bg = "#FFFFFF",
    height = 659,
    width = 1177,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

#canvas_gui2.place(x = 0, y = 0)
#GUI3
canvas_gui3 = Canvas(
    window,
    bg = "#FFFFFF",
    height = 662,
    width = 1176,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
#canvas_gui3.place(x = 0, y = 0)

#GUI4
canvas_gui4 = Canvas(
    window,
    bg = "#FFFFFF",
    height = 662,
    width = 1188,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

#GUI5
canvas_gui5 = Canvas(
    window,
    bg = "#FFFFFF",
    height = 659,
    width = 1177,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
def on_button_click(entry_widget):
    global id
    id = entry_widget.get()
    if id:
        canvas_gui1.pack_forget()
        canvas_gui2.pack()
    else:
        # Display an error message if no text is entered
        messagebox.showerror("Error", "Please enter your TikTok user ID in the textbox!")

def buton_back_continue(canvas_HT,canvas_TT):
    canvas_HT.pack_forget()
    canvas_TT.pack()

def open_file_dialog(canvas_HT,canvas_TT,list_key):
    import_file(list_key)
    buton_back_continue(canvas_HT,canvas_TT)

def relative_to_assets(ASSETS_PATH,path: str) -> Path:
    return ASSETS_PATH / Path(path)

##GUI1
ASSETS_PATH_1 = OUTPUT_PATH / Path(r"assets\frame0")
image_image_1_gui1 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_1,"image_1.png"))
image_1 = canvas_gui1.create_image(
    582.0,
    342.0,
    image=image_image_1_gui1
)

image_image_2_gui1 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_1,"image_2.png"))
image_2_gui1 = canvas_gui1.create_image(
    1120.0,
    625.0,
    image=image_image_2_gui1
)

image_image_3_gui1 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_1,"image_3.png"))
image_3 = canvas_gui1.create_image(
    745.0,
    225.0,
    image=image_image_3_gui1
)


entry_image_1_gui1 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_1,"entry_1.png"))
entry_bg_1_gui1 = canvas_gui1.create_image(
    588.0,
    385.5,
    image=entry_image_1_gui1
)
entry_1_gui1 =Entry(canvas_gui1,
    bd=0,
    bg="#EEEEEE",
    fg="#000716",
    highlightthickness=0
)
entry_1_gui1.place(
    x=374.0,
    y=347.5,
    width=428.0,
    height=77.0
)

custom_font = ("Arial", 15)
entry_1_gui1.config(font=custom_font, justify="center")

canvas_gui1.create_text(
    374.0,
    287.0,
    anchor="nw",
    text="User ID:",
    fill="#000000",
    font=("Inter ExtraLight", 23 * -1)
)

canvas_gui1.create_text(
    315.0,
    194.0,
    anchor="nw",
    text="Sign in to your\nTikTok account",
    fill="#000000",
    font=("Inter Medium", 30 * -1, "bold")
)

canvas_gui1.create_text(
    920.0,
    600.0,
    anchor="nw",
    text="livaaisoftware.com \nlivaaisoftware@gmail.com \n0293.493.294 \nLIVA SOFTWARE COMPANY",
    fill="#000000",
    font=("Inter Light", 10 * -1)
)

button_image_1_gui1 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_1,"button_1.png"))
button_1_gui1 = Button(canvas_gui1,
    image=button_image_1_gui1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: on_button_click(entry_1_gui1),
    relief="flat"
)
button_1_gui1.place(
    x=505.0,
    y=460.0,
    width=167.0,
    height=48.0
)

image_image_4_gui1 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_1,"image_4.png"))
image_4_gui1 = canvas_gui1.create_image(
    105.0,
    80.0,
    image=image_image_4_gui1
)


##GUI2
ASSETS_PATH_2 = OUTPUT_PATH / Path(r"assets\frame1")
image_image_1_gui2 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2,"image_1.png"))
image_1_gui2 = canvas_gui2.create_image(
    105.0,
    80.0,
    image=image_image_1_gui2
)

image_image_2_gui2 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2,"image_2.png"))
image_2_gui2 = canvas_gui2.create_image(
    1120.0,
    625.0,
    image=image_image_2_gui2
)

canvas_gui2.create_text(
    920.0,
    600.0,
    anchor="nw",
    text="livaaisoftware.com \nlivaaisoftware@gmail.com \n0293.493.294 \nLIVA SOFTWARE COMPANY",
    fill="#000000",
    font=("Inter Light", 10 * -1)
)

button_image_1_gui2 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2,"button_1.png"))
button_1_gui2 = Button(canvas_gui2,
    image=button_image_1_gui2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: buton_back_continue(canvas_gui2,canvas_gui1),
    relief="flat"
)
button_1_gui2.place(
    x=996.0,
    y=11.0,
    width=167.0,
    height=48.0
)

image_image_3_gui2 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2,"image_3.png"))
image_3_gui2 = canvas_gui2.create_image(
    597.0,
    341.0,
    image=image_image_3_gui2
)

canvas_gui2.create_text(
    382.0,
    186.0,
    anchor="nw",
    text="     Upload DOCX FILE\nabout your sales content!",
    fill="#000000",
    font=("Inter Medium", 35 * -1, "bold")
)


button_image_2_gui2 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2,"button_2.png"))
button_2_gui2 = Button(canvas_gui2,
    image=button_image_2_gui2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file_dialog(canvas_gui2,canvas_gui2bs,list_key),
    relief="flat"
)
button_2_gui2.place(
    x=500.0,
    y=323.0,
    width=194.0,
    height=177.0
)
#GUI2 BS
ASSETS_PATH_2bs = OUTPUT_PATH / Path(r"assets\frame2bs")
def on_button_description(entry_widget):
    global description
    description = entry_widget.get()
    canvas_gui2bs.pack_forget()
    canvas_gui3.pack()

image_image_1_gui2bs = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2bs,"image_1.png"))
image_1_gui2bs = canvas_gui2bs.create_image(
    589.0,
    328.0,
    image=image_image_1_gui2bs
)

image_image_2_gui2bs = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2bs,"image_2.png"))
image_2_gui2bs = canvas_gui2bs.create_image(
    1120.0,
    625.0,
    image=image_image_2_gui2bs
)

entry_image_1_gui2bs = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2bs,"entry_1.png"))
entry_bg_1_gui2bs = canvas_gui2bs.create_image(
    588.5,
    287.5,
    image=entry_image_1_gui2bs
)
entry_1_gui2bs = Entry(canvas_gui2bs,
    bd=0,
    bg="#EEEEEE",
    fg="#000716",
    highlightthickness=0
)
entry_1_gui2bs.place(
    x=348.0,
    y=260.0,
    width=482.0,
    height=56.0
)
custom_font = ("Arial", 15)
entry_1_gui2bs.config(font=custom_font, justify="center")

canvas_gui2bs.create_text(
    458.0,
    200.0,
    anchor="nw",
    text="Describe your AI's character",
    fill="#000000",
    font=("Inter ExtraLight", 20 * -1)
)

canvas_gui2bs.create_text(
    429.0,
    140.0,
    anchor="nw",
    text="Customize your AI MC",
    fill="#000000",
    font=("Inter Medium", 30 * -1, "bold")
)

canvas_gui2bs.create_text(
    920.0,
    600.0,
    anchor="nw",
    text="livaaisoftware.com \nlivaaisoftware@gmail.com \n0293.493.294 \nLIVA SOFTWARE COMPANY",
    fill="#000000",
    font=("Inter Light", 10 * -1)
)

image_image_3_gui2bs = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2bs,"image_3.png"))
image_3__gui2bs = canvas_gui2bs.create_image(
    105.0,
    80.0,
    image=image_image_3_gui2bs
)

button_image_3_gui2bs = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2bs,"button_3.png"))
button_3_gui2bs = Button(canvas_gui2bs,
    image=button_image_3_gui2bs,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: buton_back_continue(canvas_gui2bs,canvas_gui2),
    relief="flat"
)
button_3_gui2bs.place(
    x=996.0,
    y=11.0,
    width=167.0,
    height=48.0
)

button_image_2_gui2bs = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_2bs,"button_2.png"))
button_2_gui2bs = Button(canvas_gui2bs,
    image=button_image_2_gui2bs,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: on_button_description(entry_1_gui2bs),
    relief="flat"
)
button_2_gui2bs.place(
    x=504.0,
    y=415.0,
    width=167.0,
    height=48.0
)

#GUI3
ASSETS_PATH_3 = OUTPUT_PATH / Path(r"assets\frame2")
image_image_1_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"image_1.png"))
image_1_gui3 = canvas_gui3.create_image(
    588.0,
    200.0,
    image=image_image_1_gui3
)

image_image_2_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"image_2.png"))
image_2_gui3 = canvas_gui3.create_image(
    105.0,
    80.0,
    image=image_image_2_gui3
)

image_image_3_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"image_3.png"))
image_3_gui3 = canvas_gui3.create_image(
    1120.0,
    625.0,
    image=image_image_3_gui3
)

canvas_gui3.create_text(
    920.0,
    600.0,
    anchor="nw",
    text="livaaisoftware.com \nlivaaisoftware@gmail.com \n0293.493.294 \nLIVA SOFTWARE COMPANY",
    fill="#000000",
    font=("Inter Light", 10 * -1)
)

button_image_1_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"button_1.png"))
button_1_gui3 = Button(canvas_gui3,
    image=button_image_1_gui3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: buton_back_continue(canvas_gui3,canvas_gui2bs),
    relief="flat"
)
button_1_gui3.place(
    x=996.0,
    y=11.0,
    width=167.0,
    height=48.0
)

canvas_gui3.create_rectangle(
    373.0,
    210.0,
    803.0,
    273.0,
    fill="#C6E2FF",
    outline="")

canvas_gui3.create_text(
    390.0,
    232.0,
    anchor="nw",
    text="Thorfood_databanhang.docx",
    fill="#0C44D3",
    font=("Inter Medium", 15 * -1)
)

image_image_4_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"image_4.png"))
image_4_gui3 = canvas_gui3.create_image(
    588.0,
    461.0,
    image=image_image_4_gui3
)

image_image_5_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"image_5.png"))
image_5_gui3 = canvas_gui3.create_image(
    818.0,
    410.0,
    image=image_image_5_gui3
)

canvas_gui3.create_text(
    365.0,
    375.0,
    anchor="nw",
    text="     Start your sales\nexperience with LIVA!",
    fill="#000000",
    font=("Inter", 25 * -1)
)

canvas_gui3.create_text(
    365.0,
    117.0,
    anchor="nw",
    text="          Your sales content is below\nPlease check it out before livestreaming",
    fill="#000000",
    font=("Inter", 25 * -1)
)


button_image_2_gui3 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_3,"button_2.png"))
button_2_gui3 = Button(canvas_gui3,
    image=button_image_2_gui3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: button_run(),
    relief="flat"
)
button_2_gui3.place(
    x=420.0,
    y=460.0,
    width=134.0,
    height=90.0
)


#GUI5
ASSETS_PATH_5 = OUTPUT_PATH / Path(r"assets\frame4")
image_image_1_gui5 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_5,"image_1.png"))
image_1_gui5 = canvas_gui5.create_image(
    1120.0,
    625.0,
    image=image_image_1_gui5
)

canvas_gui5.create_text(
    920.0,
    600.0,
    anchor="nw",
    text="livaaisoftware.com \nlivaaisoftware@gmail.com \n0293.493.294 \nLIVA SOFTWARE COMPANY",
    fill="#000000",
    font=("Inter Light", 10 * -1)
)

image_image_2_gui5 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_5,"image_2.png"))
image_2_gui5 = canvas_gui5.create_image(
    105.0,
    80.0,
    image=image_image_2_gui5
)

button_image_1_gui5 = PhotoImage(
    file=relative_to_assets(ASSETS_PATH_5,"button_1.png"))
button_1_gui5 = Button(window,
    image=button_image_1_gui5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: button_gui5,
    relief="flat"
)
button_1_gui5.place(
    x=996.0,
    y=11.0,
    width=167.0,
    height=48.0
)

# Create video 1
class VideoPlayer_1:
    def __init__(self, video_path, master):
        self.video_path = video_path
        self.master = master
        self.create_widgets()

    def create_widgets(self):
        self.canvas = Canvas(self.master, width=1177, height=659)
        self.canvas.place(x=430, y=11)
        self.cap = cv2.VideoCapture(self.video_path)
        self.update()

    def update(self):
        ret, frame = self.cap.read()
        if ret:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image = Image.fromarray(frame)
            photo = ImageTk.PhotoImage(image=image)

            self.canvas.config(width=image.width, height=image.height)
            self.canvas.create_image(0, 0, anchor=tk.NW, image=photo)

            self.canvas.image = photo
            self.master.after(33, self.update)  # Update every 33 milliseconds (approximately 30 fps)
        else:
            # Video has ended, reset to the beginning
            self.cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            self.update()

def main_1():   
    video_path_1 = url(r"assets\frame4\main screen.mp4")  # Replace with your video file path
    player = VideoPlayer_1(video_path_1, window)
    window.resizable(False, False)
    window.after(2000, lambda: player.update())  # Delayed start after 2000 milliseconds (2 seconds)
    window.mainloop()

canvas_gui1.pack()
window.resizable(False, False)
window.mainloop()
